#!/usr/bin/python3
# Raise exception with a message


def raise_exception_msg(message=""):
    raise NameError(message)
